version: '3.9'

services: 
  db:
    image: postgres:latest
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment: 
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  web:
    build: .
    volumes: 
      - .:/django
    ports: 
     - "8000:8000"
    depends_on: 
     - db
    image: web:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000 
